# Generated by Django 5.0.3 on 2024-04-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0022_alter_alert_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert',
            field=models.CharField(choices=[('sweetAlert', 'sweetAlert'), ('paid', 'paid')], default='sweetAlert', max_length=24),
        ),
    ]
