# Generated by Django 5.0.3 on 2024-04-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0023_alter_alert_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='report',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
