# Generated by Django 5.0.3 on 2024-04-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0024_alert_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='report',
            new_name='status',
        ),
    ]
