# Generated by Django 5.0.3 on 2024-04-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0025_rename_report_alert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
